// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GameEventBuffer.proto

#ifndef PROTOBUF_GameEventBuffer_2eproto__INCLUDED
#define PROTOBUF_GameEventBuffer_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "EntityGameEventBuffer.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_GameEventBuffer_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsJoinSecurityGameEventBufferImpl();
void InitDefaultsJoinSecurityGameEventBuffer();
void InitDefaultsLeaveSecurityGameEventBufferImpl();
void InitDefaultsLeaveSecurityGameEventBuffer();
void InitDefaultsSecurityGameEventBufferImpl();
void InitDefaultsSecurityGameEventBuffer();
void InitDefaultsGameEventBufferImpl();
void InitDefaultsGameEventBuffer();
inline void InitDefaults() {
  InitDefaultsJoinSecurityGameEventBuffer();
  InitDefaultsLeaveSecurityGameEventBuffer();
  InitDefaultsSecurityGameEventBuffer();
  InitDefaultsGameEventBuffer();
}
}  // namespace protobuf_GameEventBuffer_2eproto
namespace usx {
namespace geofactions {
class GameEventBuffer;
class GameEventBufferDefaultTypeInternal;
extern GameEventBufferDefaultTypeInternal _GameEventBuffer_default_instance_;
class JoinSecurityGameEventBuffer;
class JoinSecurityGameEventBufferDefaultTypeInternal;
extern JoinSecurityGameEventBufferDefaultTypeInternal _JoinSecurityGameEventBuffer_default_instance_;
class LeaveSecurityGameEventBuffer;
class LeaveSecurityGameEventBufferDefaultTypeInternal;
extern LeaveSecurityGameEventBufferDefaultTypeInternal _LeaveSecurityGameEventBuffer_default_instance_;
class SecurityGameEventBuffer;
class SecurityGameEventBufferDefaultTypeInternal;
extern SecurityGameEventBufferDefaultTypeInternal _SecurityGameEventBuffer_default_instance_;
}  // namespace geofactions
}  // namespace usx
namespace usx {
namespace geofactions {

enum SecurityGameEventBuffer_SecurityGameEventBufferType {
  SecurityGameEventBuffer_SecurityGameEventBufferType_UNKNOWN = 0,
  SecurityGameEventBuffer_SecurityGameEventBufferType_JOIN = 1,
  SecurityGameEventBuffer_SecurityGameEventBufferType_LEAVE = 2
};
bool SecurityGameEventBuffer_SecurityGameEventBufferType_IsValid(int value);
const SecurityGameEventBuffer_SecurityGameEventBufferType SecurityGameEventBuffer_SecurityGameEventBufferType_SecurityGameEventBufferType_MIN = SecurityGameEventBuffer_SecurityGameEventBufferType_UNKNOWN;
const SecurityGameEventBuffer_SecurityGameEventBufferType SecurityGameEventBuffer_SecurityGameEventBufferType_SecurityGameEventBufferType_MAX = SecurityGameEventBuffer_SecurityGameEventBufferType_LEAVE;
const int SecurityGameEventBuffer_SecurityGameEventBufferType_SecurityGameEventBufferType_ARRAYSIZE = SecurityGameEventBuffer_SecurityGameEventBufferType_SecurityGameEventBufferType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SecurityGameEventBuffer_SecurityGameEventBufferType_descriptor();
inline const ::std::string& SecurityGameEventBuffer_SecurityGameEventBufferType_Name(SecurityGameEventBuffer_SecurityGameEventBufferType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SecurityGameEventBuffer_SecurityGameEventBufferType_descriptor(), value);
}
inline bool SecurityGameEventBuffer_SecurityGameEventBufferType_Parse(
    const ::std::string& name, SecurityGameEventBuffer_SecurityGameEventBufferType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SecurityGameEventBuffer_SecurityGameEventBufferType>(
    SecurityGameEventBuffer_SecurityGameEventBufferType_descriptor(), name, value);
}
enum GameEventBuffer_GameEventBufferType {
  GameEventBuffer_GameEventBufferType_UNKNOWN = 0,
  GameEventBuffer_GameEventBufferType_ENTITY = 1,
  GameEventBuffer_GameEventBufferType_SECURITY = 2
};
bool GameEventBuffer_GameEventBufferType_IsValid(int value);
const GameEventBuffer_GameEventBufferType GameEventBuffer_GameEventBufferType_GameEventBufferType_MIN = GameEventBuffer_GameEventBufferType_UNKNOWN;
const GameEventBuffer_GameEventBufferType GameEventBuffer_GameEventBufferType_GameEventBufferType_MAX = GameEventBuffer_GameEventBufferType_SECURITY;
const int GameEventBuffer_GameEventBufferType_GameEventBufferType_ARRAYSIZE = GameEventBuffer_GameEventBufferType_GameEventBufferType_MAX + 1;

const ::google::protobuf::EnumDescriptor* GameEventBuffer_GameEventBufferType_descriptor();
inline const ::std::string& GameEventBuffer_GameEventBufferType_Name(GameEventBuffer_GameEventBufferType value) {
  return ::google::protobuf::internal::NameOfEnum(
    GameEventBuffer_GameEventBufferType_descriptor(), value);
}
inline bool GameEventBuffer_GameEventBufferType_Parse(
    const ::std::string& name, GameEventBuffer_GameEventBufferType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<GameEventBuffer_GameEventBufferType>(
    GameEventBuffer_GameEventBufferType_descriptor(), name, value);
}
// ===================================================================

class JoinSecurityGameEventBuffer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:usx.geofactions.JoinSecurityGameEventBuffer) */ {
 public:
  JoinSecurityGameEventBuffer();
  virtual ~JoinSecurityGameEventBuffer();

  JoinSecurityGameEventBuffer(const JoinSecurityGameEventBuffer& from);

  inline JoinSecurityGameEventBuffer& operator=(const JoinSecurityGameEventBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  JoinSecurityGameEventBuffer(JoinSecurityGameEventBuffer&& from) noexcept
    : JoinSecurityGameEventBuffer() {
    *this = ::std::move(from);
  }

  inline JoinSecurityGameEventBuffer& operator=(JoinSecurityGameEventBuffer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const JoinSecurityGameEventBuffer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const JoinSecurityGameEventBuffer* internal_default_instance() {
    return reinterpret_cast<const JoinSecurityGameEventBuffer*>(
               &_JoinSecurityGameEventBuffer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(JoinSecurityGameEventBuffer* other);
  friend void swap(JoinSecurityGameEventBuffer& a, JoinSecurityGameEventBuffer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline JoinSecurityGameEventBuffer* New() const PROTOBUF_FINAL { return New(NULL); }

  JoinSecurityGameEventBuffer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const JoinSecurityGameEventBuffer& from);
  void MergeFrom(const JoinSecurityGameEventBuffer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(JoinSecurityGameEventBuffer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string UUID = 1;
  bool has_uuid() const;
  void clear_uuid();
  static const int kUUIDFieldNumber = 1;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  #if LANG_CXX11
  void set_uuid(::std::string&& value);
  #endif
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // @@protoc_insertion_point(class_scope:usx.geofactions.JoinSecurityGameEventBuffer)
 private:
  void set_has_uuid();
  void clear_has_uuid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  friend struct ::protobuf_GameEventBuffer_2eproto::TableStruct;
  friend void ::protobuf_GameEventBuffer_2eproto::InitDefaultsJoinSecurityGameEventBufferImpl();
};
// -------------------------------------------------------------------

class LeaveSecurityGameEventBuffer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:usx.geofactions.LeaveSecurityGameEventBuffer) */ {
 public:
  LeaveSecurityGameEventBuffer();
  virtual ~LeaveSecurityGameEventBuffer();

  LeaveSecurityGameEventBuffer(const LeaveSecurityGameEventBuffer& from);

  inline LeaveSecurityGameEventBuffer& operator=(const LeaveSecurityGameEventBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LeaveSecurityGameEventBuffer(LeaveSecurityGameEventBuffer&& from) noexcept
    : LeaveSecurityGameEventBuffer() {
    *this = ::std::move(from);
  }

  inline LeaveSecurityGameEventBuffer& operator=(LeaveSecurityGameEventBuffer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LeaveSecurityGameEventBuffer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LeaveSecurityGameEventBuffer* internal_default_instance() {
    return reinterpret_cast<const LeaveSecurityGameEventBuffer*>(
               &_LeaveSecurityGameEventBuffer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(LeaveSecurityGameEventBuffer* other);
  friend void swap(LeaveSecurityGameEventBuffer& a, LeaveSecurityGameEventBuffer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LeaveSecurityGameEventBuffer* New() const PROTOBUF_FINAL { return New(NULL); }

  LeaveSecurityGameEventBuffer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LeaveSecurityGameEventBuffer& from);
  void MergeFrom(const LeaveSecurityGameEventBuffer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LeaveSecurityGameEventBuffer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string UUID = 1;
  bool has_uuid() const;
  void clear_uuid();
  static const int kUUIDFieldNumber = 1;
  const ::std::string& uuid() const;
  void set_uuid(const ::std::string& value);
  #if LANG_CXX11
  void set_uuid(::std::string&& value);
  #endif
  void set_uuid(const char* value);
  void set_uuid(const char* value, size_t size);
  ::std::string* mutable_uuid();
  ::std::string* release_uuid();
  void set_allocated_uuid(::std::string* uuid);

  // @@protoc_insertion_point(class_scope:usx.geofactions.LeaveSecurityGameEventBuffer)
 private:
  void set_has_uuid();
  void clear_has_uuid();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr uuid_;
  friend struct ::protobuf_GameEventBuffer_2eproto::TableStruct;
  friend void ::protobuf_GameEventBuffer_2eproto::InitDefaultsLeaveSecurityGameEventBufferImpl();
};
// -------------------------------------------------------------------

class SecurityGameEventBuffer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:usx.geofactions.SecurityGameEventBuffer) */ {
 public:
  SecurityGameEventBuffer();
  virtual ~SecurityGameEventBuffer();

  SecurityGameEventBuffer(const SecurityGameEventBuffer& from);

  inline SecurityGameEventBuffer& operator=(const SecurityGameEventBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SecurityGameEventBuffer(SecurityGameEventBuffer&& from) noexcept
    : SecurityGameEventBuffer() {
    *this = ::std::move(from);
  }

  inline SecurityGameEventBuffer& operator=(SecurityGameEventBuffer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SecurityGameEventBuffer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SecurityGameEventBuffer* internal_default_instance() {
    return reinterpret_cast<const SecurityGameEventBuffer*>(
               &_SecurityGameEventBuffer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(SecurityGameEventBuffer* other);
  friend void swap(SecurityGameEventBuffer& a, SecurityGameEventBuffer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SecurityGameEventBuffer* New() const PROTOBUF_FINAL { return New(NULL); }

  SecurityGameEventBuffer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SecurityGameEventBuffer& from);
  void MergeFrom(const SecurityGameEventBuffer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SecurityGameEventBuffer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef SecurityGameEventBuffer_SecurityGameEventBufferType SecurityGameEventBufferType;
  static const SecurityGameEventBufferType UNKNOWN =
    SecurityGameEventBuffer_SecurityGameEventBufferType_UNKNOWN;
  static const SecurityGameEventBufferType JOIN =
    SecurityGameEventBuffer_SecurityGameEventBufferType_JOIN;
  static const SecurityGameEventBufferType LEAVE =
    SecurityGameEventBuffer_SecurityGameEventBufferType_LEAVE;
  static inline bool SecurityGameEventBufferType_IsValid(int value) {
    return SecurityGameEventBuffer_SecurityGameEventBufferType_IsValid(value);
  }
  static const SecurityGameEventBufferType SecurityGameEventBufferType_MIN =
    SecurityGameEventBuffer_SecurityGameEventBufferType_SecurityGameEventBufferType_MIN;
  static const SecurityGameEventBufferType SecurityGameEventBufferType_MAX =
    SecurityGameEventBuffer_SecurityGameEventBufferType_SecurityGameEventBufferType_MAX;
  static const int SecurityGameEventBufferType_ARRAYSIZE =
    SecurityGameEventBuffer_SecurityGameEventBufferType_SecurityGameEventBufferType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  SecurityGameEventBufferType_descriptor() {
    return SecurityGameEventBuffer_SecurityGameEventBufferType_descriptor();
  }
  static inline const ::std::string& SecurityGameEventBufferType_Name(SecurityGameEventBufferType value) {
    return SecurityGameEventBuffer_SecurityGameEventBufferType_Name(value);
  }
  static inline bool SecurityGameEventBufferType_Parse(const ::std::string& name,
      SecurityGameEventBufferType* value) {
    return SecurityGameEventBuffer_SecurityGameEventBufferType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .usx.geofactions.JoinSecurityGameEventBuffer joinSecurityGameEventBuffer = 3;
  bool has_joinsecuritygameeventbuffer() const;
  void clear_joinsecuritygameeventbuffer();
  static const int kJoinSecurityGameEventBufferFieldNumber = 3;
  const ::usx::geofactions::JoinSecurityGameEventBuffer& joinsecuritygameeventbuffer() const;
  ::usx::geofactions::JoinSecurityGameEventBuffer* release_joinsecuritygameeventbuffer();
  ::usx::geofactions::JoinSecurityGameEventBuffer* mutable_joinsecuritygameeventbuffer();
  void set_allocated_joinsecuritygameeventbuffer(::usx::geofactions::JoinSecurityGameEventBuffer* joinsecuritygameeventbuffer);

  // optional .usx.geofactions.LeaveSecurityGameEventBuffer leaveSecurityGameEventBuffer = 4;
  bool has_leavesecuritygameeventbuffer() const;
  void clear_leavesecuritygameeventbuffer();
  static const int kLeaveSecurityGameEventBufferFieldNumber = 4;
  const ::usx::geofactions::LeaveSecurityGameEventBuffer& leavesecuritygameeventbuffer() const;
  ::usx::geofactions::LeaveSecurityGameEventBuffer* release_leavesecuritygameeventbuffer();
  ::usx::geofactions::LeaveSecurityGameEventBuffer* mutable_leavesecuritygameeventbuffer();
  void set_allocated_leavesecuritygameeventbuffer(::usx::geofactions::LeaveSecurityGameEventBuffer* leavesecuritygameeventbuffer);

  // required .usx.geofactions.SecurityGameEventBuffer.SecurityGameEventBufferType type = 1 [default = UNKNOWN];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType type() const;
  void set_type(::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType value);

  // @@protoc_insertion_point(class_scope:usx.geofactions.SecurityGameEventBuffer)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_joinsecuritygameeventbuffer();
  void clear_has_joinsecuritygameeventbuffer();
  void set_has_leavesecuritygameeventbuffer();
  void clear_has_leavesecuritygameeventbuffer();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::usx::geofactions::JoinSecurityGameEventBuffer* joinsecuritygameeventbuffer_;
  ::usx::geofactions::LeaveSecurityGameEventBuffer* leavesecuritygameeventbuffer_;
  int type_;
  friend struct ::protobuf_GameEventBuffer_2eproto::TableStruct;
  friend void ::protobuf_GameEventBuffer_2eproto::InitDefaultsSecurityGameEventBufferImpl();
};
// -------------------------------------------------------------------

class GameEventBuffer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:usx.geofactions.GameEventBuffer) */ {
 public:
  GameEventBuffer();
  virtual ~GameEventBuffer();

  GameEventBuffer(const GameEventBuffer& from);

  inline GameEventBuffer& operator=(const GameEventBuffer& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameEventBuffer(GameEventBuffer&& from) noexcept
    : GameEventBuffer() {
    *this = ::std::move(from);
  }

  inline GameEventBuffer& operator=(GameEventBuffer&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GameEventBuffer& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameEventBuffer* internal_default_instance() {
    return reinterpret_cast<const GameEventBuffer*>(
               &_GameEventBuffer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(GameEventBuffer* other);
  friend void swap(GameEventBuffer& a, GameEventBuffer& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameEventBuffer* New() const PROTOBUF_FINAL { return New(NULL); }

  GameEventBuffer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GameEventBuffer& from);
  void MergeFrom(const GameEventBuffer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GameEventBuffer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef GameEventBuffer_GameEventBufferType GameEventBufferType;
  static const GameEventBufferType UNKNOWN =
    GameEventBuffer_GameEventBufferType_UNKNOWN;
  static const GameEventBufferType ENTITY =
    GameEventBuffer_GameEventBufferType_ENTITY;
  static const GameEventBufferType SECURITY =
    GameEventBuffer_GameEventBufferType_SECURITY;
  static inline bool GameEventBufferType_IsValid(int value) {
    return GameEventBuffer_GameEventBufferType_IsValid(value);
  }
  static const GameEventBufferType GameEventBufferType_MIN =
    GameEventBuffer_GameEventBufferType_GameEventBufferType_MIN;
  static const GameEventBufferType GameEventBufferType_MAX =
    GameEventBuffer_GameEventBufferType_GameEventBufferType_MAX;
  static const int GameEventBufferType_ARRAYSIZE =
    GameEventBuffer_GameEventBufferType_GameEventBufferType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  GameEventBufferType_descriptor() {
    return GameEventBuffer_GameEventBufferType_descriptor();
  }
  static inline const ::std::string& GameEventBufferType_Name(GameEventBufferType value) {
    return GameEventBuffer_GameEventBufferType_Name(value);
  }
  static inline bool GameEventBufferType_Parse(const ::std::string& name,
      GameEventBufferType* value) {
    return GameEventBuffer_GameEventBufferType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // optional .usx.geofactions.EntityGameEventBuffer entityGameEventBuffer = 2;
  bool has_entitygameeventbuffer() const;
  void clear_entitygameeventbuffer();
  static const int kEntityGameEventBufferFieldNumber = 2;
  const ::usx::geofactions::EntityGameEventBuffer& entitygameeventbuffer() const;
  ::usx::geofactions::EntityGameEventBuffer* release_entitygameeventbuffer();
  ::usx::geofactions::EntityGameEventBuffer* mutable_entitygameeventbuffer();
  void set_allocated_entitygameeventbuffer(::usx::geofactions::EntityGameEventBuffer* entitygameeventbuffer);

  // optional .usx.geofactions.SecurityGameEventBuffer securityGameEventBuffer = 3;
  bool has_securitygameeventbuffer() const;
  void clear_securitygameeventbuffer();
  static const int kSecurityGameEventBufferFieldNumber = 3;
  const ::usx::geofactions::SecurityGameEventBuffer& securitygameeventbuffer() const;
  ::usx::geofactions::SecurityGameEventBuffer* release_securitygameeventbuffer();
  ::usx::geofactions::SecurityGameEventBuffer* mutable_securitygameeventbuffer();
  void set_allocated_securitygameeventbuffer(::usx::geofactions::SecurityGameEventBuffer* securitygameeventbuffer);

  // required .usx.geofactions.GameEventBuffer.GameEventBufferType type = 1 [default = UNKNOWN];
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::usx::geofactions::GameEventBuffer_GameEventBufferType type() const;
  void set_type(::usx::geofactions::GameEventBuffer_GameEventBufferType value);

  // @@protoc_insertion_point(class_scope:usx.geofactions.GameEventBuffer)
 private:
  void set_has_type();
  void clear_has_type();
  void set_has_entitygameeventbuffer();
  void clear_has_entitygameeventbuffer();
  void set_has_securitygameeventbuffer();
  void clear_has_securitygameeventbuffer();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::usx::geofactions::EntityGameEventBuffer* entitygameeventbuffer_;
  ::usx::geofactions::SecurityGameEventBuffer* securitygameeventbuffer_;
  int type_;
  friend struct ::protobuf_GameEventBuffer_2eproto::TableStruct;
  friend void ::protobuf_GameEventBuffer_2eproto::InitDefaultsGameEventBufferImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// JoinSecurityGameEventBuffer

// required string UUID = 1;
inline bool JoinSecurityGameEventBuffer::has_uuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void JoinSecurityGameEventBuffer::set_has_uuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void JoinSecurityGameEventBuffer::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void JoinSecurityGameEventBuffer::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_uuid();
}
inline const ::std::string& JoinSecurityGameEventBuffer::uuid() const {
  // @@protoc_insertion_point(field_get:usx.geofactions.JoinSecurityGameEventBuffer.UUID)
  return uuid_.GetNoArena();
}
inline void JoinSecurityGameEventBuffer::set_uuid(const ::std::string& value) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:usx.geofactions.JoinSecurityGameEventBuffer.UUID)
}
#if LANG_CXX11
inline void JoinSecurityGameEventBuffer::set_uuid(::std::string&& value) {
  set_has_uuid();
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:usx.geofactions.JoinSecurityGameEventBuffer.UUID)
}
#endif
inline void JoinSecurityGameEventBuffer::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:usx.geofactions.JoinSecurityGameEventBuffer.UUID)
}
inline void JoinSecurityGameEventBuffer::set_uuid(const char* value, size_t size) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:usx.geofactions.JoinSecurityGameEventBuffer.UUID)
}
inline ::std::string* JoinSecurityGameEventBuffer::mutable_uuid() {
  set_has_uuid();
  // @@protoc_insertion_point(field_mutable:usx.geofactions.JoinSecurityGameEventBuffer.UUID)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* JoinSecurityGameEventBuffer::release_uuid() {
  // @@protoc_insertion_point(field_release:usx.geofactions.JoinSecurityGameEventBuffer.UUID)
  clear_has_uuid();
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void JoinSecurityGameEventBuffer::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    set_has_uuid();
  } else {
    clear_has_uuid();
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:usx.geofactions.JoinSecurityGameEventBuffer.UUID)
}

// -------------------------------------------------------------------

// LeaveSecurityGameEventBuffer

// required string UUID = 1;
inline bool LeaveSecurityGameEventBuffer::has_uuid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LeaveSecurityGameEventBuffer::set_has_uuid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LeaveSecurityGameEventBuffer::clear_has_uuid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LeaveSecurityGameEventBuffer::clear_uuid() {
  uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_uuid();
}
inline const ::std::string& LeaveSecurityGameEventBuffer::uuid() const {
  // @@protoc_insertion_point(field_get:usx.geofactions.LeaveSecurityGameEventBuffer.UUID)
  return uuid_.GetNoArena();
}
inline void LeaveSecurityGameEventBuffer::set_uuid(const ::std::string& value) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:usx.geofactions.LeaveSecurityGameEventBuffer.UUID)
}
#if LANG_CXX11
inline void LeaveSecurityGameEventBuffer::set_uuid(::std::string&& value) {
  set_has_uuid();
  uuid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:usx.geofactions.LeaveSecurityGameEventBuffer.UUID)
}
#endif
inline void LeaveSecurityGameEventBuffer::set_uuid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:usx.geofactions.LeaveSecurityGameEventBuffer.UUID)
}
inline void LeaveSecurityGameEventBuffer::set_uuid(const char* value, size_t size) {
  set_has_uuid();
  uuid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:usx.geofactions.LeaveSecurityGameEventBuffer.UUID)
}
inline ::std::string* LeaveSecurityGameEventBuffer::mutable_uuid() {
  set_has_uuid();
  // @@protoc_insertion_point(field_mutable:usx.geofactions.LeaveSecurityGameEventBuffer.UUID)
  return uuid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LeaveSecurityGameEventBuffer::release_uuid() {
  // @@protoc_insertion_point(field_release:usx.geofactions.LeaveSecurityGameEventBuffer.UUID)
  clear_has_uuid();
  return uuid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LeaveSecurityGameEventBuffer::set_allocated_uuid(::std::string* uuid) {
  if (uuid != NULL) {
    set_has_uuid();
  } else {
    clear_has_uuid();
  }
  uuid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), uuid);
  // @@protoc_insertion_point(field_set_allocated:usx.geofactions.LeaveSecurityGameEventBuffer.UUID)
}

// -------------------------------------------------------------------

// SecurityGameEventBuffer

// required .usx.geofactions.SecurityGameEventBuffer.SecurityGameEventBufferType type = 1 [default = UNKNOWN];
inline bool SecurityGameEventBuffer::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SecurityGameEventBuffer::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SecurityGameEventBuffer::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SecurityGameEventBuffer::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType SecurityGameEventBuffer::type() const {
  // @@protoc_insertion_point(field_get:usx.geofactions.SecurityGameEventBuffer.type)
  return static_cast< ::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType >(type_);
}
inline void SecurityGameEventBuffer::set_type(::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType value) {
  assert(::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:usx.geofactions.SecurityGameEventBuffer.type)
}

// optional .usx.geofactions.JoinSecurityGameEventBuffer joinSecurityGameEventBuffer = 3;
inline bool SecurityGameEventBuffer::has_joinsecuritygameeventbuffer() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SecurityGameEventBuffer::set_has_joinsecuritygameeventbuffer() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SecurityGameEventBuffer::clear_has_joinsecuritygameeventbuffer() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SecurityGameEventBuffer::clear_joinsecuritygameeventbuffer() {
  if (joinsecuritygameeventbuffer_ != NULL) joinsecuritygameeventbuffer_->Clear();
  clear_has_joinsecuritygameeventbuffer();
}
inline const ::usx::geofactions::JoinSecurityGameEventBuffer& SecurityGameEventBuffer::joinsecuritygameeventbuffer() const {
  const ::usx::geofactions::JoinSecurityGameEventBuffer* p = joinsecuritygameeventbuffer_;
  // @@protoc_insertion_point(field_get:usx.geofactions.SecurityGameEventBuffer.joinSecurityGameEventBuffer)
  return p != NULL ? *p : *reinterpret_cast<const ::usx::geofactions::JoinSecurityGameEventBuffer*>(
      &::usx::geofactions::_JoinSecurityGameEventBuffer_default_instance_);
}
inline ::usx::geofactions::JoinSecurityGameEventBuffer* SecurityGameEventBuffer::release_joinsecuritygameeventbuffer() {
  // @@protoc_insertion_point(field_release:usx.geofactions.SecurityGameEventBuffer.joinSecurityGameEventBuffer)
  clear_has_joinsecuritygameeventbuffer();
  ::usx::geofactions::JoinSecurityGameEventBuffer* temp = joinsecuritygameeventbuffer_;
  joinsecuritygameeventbuffer_ = NULL;
  return temp;
}
inline ::usx::geofactions::JoinSecurityGameEventBuffer* SecurityGameEventBuffer::mutable_joinsecuritygameeventbuffer() {
  set_has_joinsecuritygameeventbuffer();
  if (joinsecuritygameeventbuffer_ == NULL) {
    joinsecuritygameeventbuffer_ = new ::usx::geofactions::JoinSecurityGameEventBuffer;
  }
  // @@protoc_insertion_point(field_mutable:usx.geofactions.SecurityGameEventBuffer.joinSecurityGameEventBuffer)
  return joinsecuritygameeventbuffer_;
}
inline void SecurityGameEventBuffer::set_allocated_joinsecuritygameeventbuffer(::usx::geofactions::JoinSecurityGameEventBuffer* joinsecuritygameeventbuffer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete joinsecuritygameeventbuffer_;
  }
  if (joinsecuritygameeventbuffer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      joinsecuritygameeventbuffer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, joinsecuritygameeventbuffer, submessage_arena);
    }
    set_has_joinsecuritygameeventbuffer();
  } else {
    clear_has_joinsecuritygameeventbuffer();
  }
  joinsecuritygameeventbuffer_ = joinsecuritygameeventbuffer;
  // @@protoc_insertion_point(field_set_allocated:usx.geofactions.SecurityGameEventBuffer.joinSecurityGameEventBuffer)
}

// optional .usx.geofactions.LeaveSecurityGameEventBuffer leaveSecurityGameEventBuffer = 4;
inline bool SecurityGameEventBuffer::has_leavesecuritygameeventbuffer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SecurityGameEventBuffer::set_has_leavesecuritygameeventbuffer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SecurityGameEventBuffer::clear_has_leavesecuritygameeventbuffer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SecurityGameEventBuffer::clear_leavesecuritygameeventbuffer() {
  if (leavesecuritygameeventbuffer_ != NULL) leavesecuritygameeventbuffer_->Clear();
  clear_has_leavesecuritygameeventbuffer();
}
inline const ::usx::geofactions::LeaveSecurityGameEventBuffer& SecurityGameEventBuffer::leavesecuritygameeventbuffer() const {
  const ::usx::geofactions::LeaveSecurityGameEventBuffer* p = leavesecuritygameeventbuffer_;
  // @@protoc_insertion_point(field_get:usx.geofactions.SecurityGameEventBuffer.leaveSecurityGameEventBuffer)
  return p != NULL ? *p : *reinterpret_cast<const ::usx::geofactions::LeaveSecurityGameEventBuffer*>(
      &::usx::geofactions::_LeaveSecurityGameEventBuffer_default_instance_);
}
inline ::usx::geofactions::LeaveSecurityGameEventBuffer* SecurityGameEventBuffer::release_leavesecuritygameeventbuffer() {
  // @@protoc_insertion_point(field_release:usx.geofactions.SecurityGameEventBuffer.leaveSecurityGameEventBuffer)
  clear_has_leavesecuritygameeventbuffer();
  ::usx::geofactions::LeaveSecurityGameEventBuffer* temp = leavesecuritygameeventbuffer_;
  leavesecuritygameeventbuffer_ = NULL;
  return temp;
}
inline ::usx::geofactions::LeaveSecurityGameEventBuffer* SecurityGameEventBuffer::mutable_leavesecuritygameeventbuffer() {
  set_has_leavesecuritygameeventbuffer();
  if (leavesecuritygameeventbuffer_ == NULL) {
    leavesecuritygameeventbuffer_ = new ::usx::geofactions::LeaveSecurityGameEventBuffer;
  }
  // @@protoc_insertion_point(field_mutable:usx.geofactions.SecurityGameEventBuffer.leaveSecurityGameEventBuffer)
  return leavesecuritygameeventbuffer_;
}
inline void SecurityGameEventBuffer::set_allocated_leavesecuritygameeventbuffer(::usx::geofactions::LeaveSecurityGameEventBuffer* leavesecuritygameeventbuffer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete leavesecuritygameeventbuffer_;
  }
  if (leavesecuritygameeventbuffer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      leavesecuritygameeventbuffer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, leavesecuritygameeventbuffer, submessage_arena);
    }
    set_has_leavesecuritygameeventbuffer();
  } else {
    clear_has_leavesecuritygameeventbuffer();
  }
  leavesecuritygameeventbuffer_ = leavesecuritygameeventbuffer;
  // @@protoc_insertion_point(field_set_allocated:usx.geofactions.SecurityGameEventBuffer.leaveSecurityGameEventBuffer)
}

// -------------------------------------------------------------------

// GameEventBuffer

// required .usx.geofactions.GameEventBuffer.GameEventBufferType type = 1 [default = UNKNOWN];
inline bool GameEventBuffer::has_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GameEventBuffer::set_has_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GameEventBuffer::clear_has_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GameEventBuffer::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::usx::geofactions::GameEventBuffer_GameEventBufferType GameEventBuffer::type() const {
  // @@protoc_insertion_point(field_get:usx.geofactions.GameEventBuffer.type)
  return static_cast< ::usx::geofactions::GameEventBuffer_GameEventBufferType >(type_);
}
inline void GameEventBuffer::set_type(::usx::geofactions::GameEventBuffer_GameEventBufferType value) {
  assert(::usx::geofactions::GameEventBuffer_GameEventBufferType_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:usx.geofactions.GameEventBuffer.type)
}

// optional .usx.geofactions.EntityGameEventBuffer entityGameEventBuffer = 2;
inline bool GameEventBuffer::has_entitygameeventbuffer() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GameEventBuffer::set_has_entitygameeventbuffer() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GameEventBuffer::clear_has_entitygameeventbuffer() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::usx::geofactions::EntityGameEventBuffer& GameEventBuffer::entitygameeventbuffer() const {
  const ::usx::geofactions::EntityGameEventBuffer* p = entitygameeventbuffer_;
  // @@protoc_insertion_point(field_get:usx.geofactions.GameEventBuffer.entityGameEventBuffer)
  return p != NULL ? *p : *reinterpret_cast<const ::usx::geofactions::EntityGameEventBuffer*>(
      &::usx::geofactions::_EntityGameEventBuffer_default_instance_);
}
inline ::usx::geofactions::EntityGameEventBuffer* GameEventBuffer::release_entitygameeventbuffer() {
  // @@protoc_insertion_point(field_release:usx.geofactions.GameEventBuffer.entityGameEventBuffer)
  clear_has_entitygameeventbuffer();
  ::usx::geofactions::EntityGameEventBuffer* temp = entitygameeventbuffer_;
  entitygameeventbuffer_ = NULL;
  return temp;
}
inline ::usx::geofactions::EntityGameEventBuffer* GameEventBuffer::mutable_entitygameeventbuffer() {
  set_has_entitygameeventbuffer();
  if (entitygameeventbuffer_ == NULL) {
    entitygameeventbuffer_ = new ::usx::geofactions::EntityGameEventBuffer;
  }
  // @@protoc_insertion_point(field_mutable:usx.geofactions.GameEventBuffer.entityGameEventBuffer)
  return entitygameeventbuffer_;
}
inline void GameEventBuffer::set_allocated_entitygameeventbuffer(::usx::geofactions::EntityGameEventBuffer* entitygameeventbuffer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(entitygameeventbuffer_);
  }
  if (entitygameeventbuffer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      entitygameeventbuffer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, entitygameeventbuffer, submessage_arena);
    }
    set_has_entitygameeventbuffer();
  } else {
    clear_has_entitygameeventbuffer();
  }
  entitygameeventbuffer_ = entitygameeventbuffer;
  // @@protoc_insertion_point(field_set_allocated:usx.geofactions.GameEventBuffer.entityGameEventBuffer)
}

// optional .usx.geofactions.SecurityGameEventBuffer securityGameEventBuffer = 3;
inline bool GameEventBuffer::has_securitygameeventbuffer() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GameEventBuffer::set_has_securitygameeventbuffer() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GameEventBuffer::clear_has_securitygameeventbuffer() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GameEventBuffer::clear_securitygameeventbuffer() {
  if (securitygameeventbuffer_ != NULL) securitygameeventbuffer_->Clear();
  clear_has_securitygameeventbuffer();
}
inline const ::usx::geofactions::SecurityGameEventBuffer& GameEventBuffer::securitygameeventbuffer() const {
  const ::usx::geofactions::SecurityGameEventBuffer* p = securitygameeventbuffer_;
  // @@protoc_insertion_point(field_get:usx.geofactions.GameEventBuffer.securityGameEventBuffer)
  return p != NULL ? *p : *reinterpret_cast<const ::usx::geofactions::SecurityGameEventBuffer*>(
      &::usx::geofactions::_SecurityGameEventBuffer_default_instance_);
}
inline ::usx::geofactions::SecurityGameEventBuffer* GameEventBuffer::release_securitygameeventbuffer() {
  // @@protoc_insertion_point(field_release:usx.geofactions.GameEventBuffer.securityGameEventBuffer)
  clear_has_securitygameeventbuffer();
  ::usx::geofactions::SecurityGameEventBuffer* temp = securitygameeventbuffer_;
  securitygameeventbuffer_ = NULL;
  return temp;
}
inline ::usx::geofactions::SecurityGameEventBuffer* GameEventBuffer::mutable_securitygameeventbuffer() {
  set_has_securitygameeventbuffer();
  if (securitygameeventbuffer_ == NULL) {
    securitygameeventbuffer_ = new ::usx::geofactions::SecurityGameEventBuffer;
  }
  // @@protoc_insertion_point(field_mutable:usx.geofactions.GameEventBuffer.securityGameEventBuffer)
  return securitygameeventbuffer_;
}
inline void GameEventBuffer::set_allocated_securitygameeventbuffer(::usx::geofactions::SecurityGameEventBuffer* securitygameeventbuffer) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete securitygameeventbuffer_;
  }
  if (securitygameeventbuffer) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      securitygameeventbuffer = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, securitygameeventbuffer, submessage_arena);
    }
    set_has_securitygameeventbuffer();
  } else {
    clear_has_securitygameeventbuffer();
  }
  securitygameeventbuffer_ = securitygameeventbuffer;
  // @@protoc_insertion_point(field_set_allocated:usx.geofactions.GameEventBuffer.securityGameEventBuffer)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace geofactions
}  // namespace usx

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType>() {
  return ::usx::geofactions::SecurityGameEventBuffer_SecurityGameEventBufferType_descriptor();
}
template <> struct is_proto_enum< ::usx::geofactions::GameEventBuffer_GameEventBufferType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::usx::geofactions::GameEventBuffer_GameEventBufferType>() {
  return ::usx::geofactions::GameEventBuffer_GameEventBufferType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GameEventBuffer_2eproto__INCLUDED
