// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RawInputCommandBuffer.proto

#include "RawInputCommandBuffer.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_DualStickRawInputCommandBuffer_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_DualStickRawInputCommandBuffer_DualStickRawInputCommandBuffer_2eproto;
namespace usx {
namespace geofactions {
class RawInputCommandBufferDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RawInputCommandBuffer> _instance;
} _RawInputCommandBuffer_default_instance_;
}  // namespace geofactions
}  // namespace usx
static void InitDefaultsscc_info_RawInputCommandBuffer_RawInputCommandBuffer_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::usx::geofactions::_RawInputCommandBuffer_default_instance_;
    new (ptr) ::usx::geofactions::RawInputCommandBuffer();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::usx::geofactions::RawInputCommandBuffer::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RawInputCommandBuffer_RawInputCommandBuffer_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_RawInputCommandBuffer_RawInputCommandBuffer_2eproto}, {
      &scc_info_DualStickRawInputCommandBuffer_DualStickRawInputCommandBuffer_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_RawInputCommandBuffer_2eproto[1];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_RawInputCommandBuffer_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_RawInputCommandBuffer_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_RawInputCommandBuffer_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::usx::geofactions::RawInputCommandBuffer, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::usx::geofactions::RawInputCommandBuffer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::usx::geofactions::RawInputCommandBuffer, type_),
  PROTOBUF_FIELD_OFFSET(::usx::geofactions::RawInputCommandBuffer, uuid_),
  PROTOBUF_FIELD_OFFSET(::usx::geofactions::RawInputCommandBuffer, dualstickrawinputcommandbuffer_),
  2,
  0,
  1,
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::usx::geofactions::RawInputCommandBuffer)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::usx::geofactions::_RawInputCommandBuffer_default_instance_),
};

const char descriptor_table_protodef_RawInputCommandBuffer_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\033RawInputCommandBuffer.proto\022\017usx.geofa"
  "ctions\032$DualStickRawInputCommandBuffer.p"
  "roto\"\220\002\n\025RawInputCommandBuffer\022W\n\004type\030\001"
  " \002(\0162@.usx.geofactions.RawInputCommandBu"
  "ffer.RawInputCommandBufferType:\007UNKNOWN\022"
  "\014\n\004UUID\030\002 \002(\t\022W\n\036dualStickRawInputComman"
  "dBuffer\030\003 \001(\0132/.usx.geofactions.DualStic"
  "kRawInputCommandBuffer\"7\n\031RawInputComman"
  "dBufferType\022\013\n\007UNKNOWN\020\000\022\r\n\tDUALSTICK\020\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_RawInputCommandBuffer_2eproto_deps[1] = {
  &::descriptor_table_DualStickRawInputCommandBuffer_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_RawInputCommandBuffer_2eproto_sccs[1] = {
  &scc_info_RawInputCommandBuffer_RawInputCommandBuffer_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_RawInputCommandBuffer_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RawInputCommandBuffer_2eproto = {
  false, false, descriptor_table_protodef_RawInputCommandBuffer_2eproto, "RawInputCommandBuffer.proto", 359,
  &descriptor_table_RawInputCommandBuffer_2eproto_once, descriptor_table_RawInputCommandBuffer_2eproto_sccs, descriptor_table_RawInputCommandBuffer_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_RawInputCommandBuffer_2eproto::offsets,
  file_level_metadata_RawInputCommandBuffer_2eproto, 1, file_level_enum_descriptors_RawInputCommandBuffer_2eproto, file_level_service_descriptors_RawInputCommandBuffer_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_RawInputCommandBuffer_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_RawInputCommandBuffer_2eproto)), true);
namespace usx {
namespace geofactions {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RawInputCommandBuffer_RawInputCommandBufferType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_RawInputCommandBuffer_2eproto);
  return file_level_enum_descriptors_RawInputCommandBuffer_2eproto[0];
}
bool RawInputCommandBuffer_RawInputCommandBufferType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr RawInputCommandBuffer_RawInputCommandBufferType RawInputCommandBuffer::UNKNOWN;
constexpr RawInputCommandBuffer_RawInputCommandBufferType RawInputCommandBuffer::DUALSTICK;
constexpr RawInputCommandBuffer_RawInputCommandBufferType RawInputCommandBuffer::RawInputCommandBufferType_MIN;
constexpr RawInputCommandBuffer_RawInputCommandBufferType RawInputCommandBuffer::RawInputCommandBufferType_MAX;
constexpr int RawInputCommandBuffer::RawInputCommandBufferType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void RawInputCommandBuffer::InitAsDefaultInstance() {
  ::usx::geofactions::_RawInputCommandBuffer_default_instance_._instance.get_mutable()->dualstickrawinputcommandbuffer_ = const_cast< ::usx::geofactions::DualStickRawInputCommandBuffer*>(
      ::usx::geofactions::DualStickRawInputCommandBuffer::internal_default_instance());
}
class RawInputCommandBuffer::_Internal {
 public:
  using HasBits = decltype(std::declval<RawInputCommandBuffer>()._has_bits_);
  static void set_has_type(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_uuid(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::usx::geofactions::DualStickRawInputCommandBuffer& dualstickrawinputcommandbuffer(const RawInputCommandBuffer* msg);
  static void set_has_dualstickrawinputcommandbuffer(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000005) ^ 0x00000005) != 0;
  }
};

const ::usx::geofactions::DualStickRawInputCommandBuffer&
RawInputCommandBuffer::_Internal::dualstickrawinputcommandbuffer(const RawInputCommandBuffer* msg) {
  return *msg->dualstickrawinputcommandbuffer_;
}
void RawInputCommandBuffer::clear_dualstickrawinputcommandbuffer() {
  if (dualstickrawinputcommandbuffer_ != nullptr) dualstickrawinputcommandbuffer_->Clear();
  _has_bits_[0] &= ~0x00000002u;
}
RawInputCommandBuffer::RawInputCommandBuffer(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:usx.geofactions.RawInputCommandBuffer)
}
RawInputCommandBuffer::RawInputCommandBuffer(const RawInputCommandBuffer& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (from._internal_has_uuid()) {
    uuid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_uuid(),
      GetArena());
  }
  if (from._internal_has_dualstickrawinputcommandbuffer()) {
    dualstickrawinputcommandbuffer_ = new ::usx::geofactions::DualStickRawInputCommandBuffer(*from.dualstickrawinputcommandbuffer_);
  } else {
    dualstickrawinputcommandbuffer_ = nullptr;
  }
  type_ = from.type_;
  // @@protoc_insertion_point(copy_constructor:usx.geofactions.RawInputCommandBuffer)
}

void RawInputCommandBuffer::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RawInputCommandBuffer_RawInputCommandBuffer_2eproto.base);
  uuid_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&dualstickrawinputcommandbuffer_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&dualstickrawinputcommandbuffer_)) + sizeof(type_));
}

RawInputCommandBuffer::~RawInputCommandBuffer() {
  // @@protoc_insertion_point(destructor:usx.geofactions.RawInputCommandBuffer)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RawInputCommandBuffer::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  uuid_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete dualstickrawinputcommandbuffer_;
}

void RawInputCommandBuffer::ArenaDtor(void* object) {
  RawInputCommandBuffer* _this = reinterpret_cast< RawInputCommandBuffer* >(object);
  (void)_this;
}
void RawInputCommandBuffer::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RawInputCommandBuffer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RawInputCommandBuffer& RawInputCommandBuffer::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RawInputCommandBuffer_RawInputCommandBuffer_2eproto.base);
  return *internal_default_instance();
}


void RawInputCommandBuffer::Clear() {
// @@protoc_insertion_point(message_clear_start:usx.geofactions.RawInputCommandBuffer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      uuid_.ClearNonDefaultToEmpty();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(dualstickrawinputcommandbuffer_ != nullptr);
      dualstickrawinputcommandbuffer_->Clear();
    }
  }
  type_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RawInputCommandBuffer::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .usx.geofactions.RawInputCommandBuffer.RawInputCommandBufferType type = 1 [default = UNKNOWN];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::usx::geofactions::RawInputCommandBuffer_RawInputCommandBufferType_IsValid(val))) {
            _internal_set_type(static_cast<::usx::geofactions::RawInputCommandBuffer_RawInputCommandBufferType>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else goto handle_unusual;
        continue;
      // required string UUID = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_uuid();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          #ifndef NDEBUG
          ::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "usx.geofactions.RawInputCommandBuffer.UUID");
          #endif  // !NDEBUG
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // optional .usx.geofactions.DualStickRawInputCommandBuffer dualStickRawInputCommandBuffer = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_dualstickrawinputcommandbuffer(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RawInputCommandBuffer::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:usx.geofactions.RawInputCommandBuffer)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .usx.geofactions.RawInputCommandBuffer.RawInputCommandBufferType type = 1 [default = UNKNOWN];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // required string UUID = 2;
  if (cached_has_bits & 0x00000001u) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
      this->_internal_uuid().data(), static_cast<int>(this->_internal_uuid().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
      "usx.geofactions.RawInputCommandBuffer.UUID");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_uuid(), target);
  }

  // optional .usx.geofactions.DualStickRawInputCommandBuffer dualStickRawInputCommandBuffer = 3;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::dualstickrawinputcommandbuffer(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:usx.geofactions.RawInputCommandBuffer)
  return target;
}

size_t RawInputCommandBuffer::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:usx.geofactions.RawInputCommandBuffer)
  size_t total_size = 0;

  if (_internal_has_uuid()) {
    // required string UUID = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_uuid());
  }

  if (_internal_has_type()) {
    // required .usx.geofactions.RawInputCommandBuffer.RawInputCommandBufferType type = 1 [default = UNKNOWN];
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  return total_size;
}
size_t RawInputCommandBuffer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:usx.geofactions.RawInputCommandBuffer)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000005) ^ 0x00000005) == 0) {  // All required fields are present.
    // required string UUID = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_uuid());

    // required .usx.geofactions.RawInputCommandBuffer.RawInputCommandBufferType type = 1 [default = UNKNOWN];
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional .usx.geofactions.DualStickRawInputCommandBuffer dualStickRawInputCommandBuffer = 3;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000002u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *dualstickrawinputcommandbuffer_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RawInputCommandBuffer::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:usx.geofactions.RawInputCommandBuffer)
  GOOGLE_DCHECK_NE(&from, this);
  const RawInputCommandBuffer* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RawInputCommandBuffer>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:usx.geofactions.RawInputCommandBuffer)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:usx.geofactions.RawInputCommandBuffer)
    MergeFrom(*source);
  }
}

void RawInputCommandBuffer::MergeFrom(const RawInputCommandBuffer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:usx.geofactions.RawInputCommandBuffer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_uuid(from._internal_uuid());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_dualstickrawinputcommandbuffer()->::usx::geofactions::DualStickRawInputCommandBuffer::MergeFrom(from._internal_dualstickrawinputcommandbuffer());
    }
    if (cached_has_bits & 0x00000004u) {
      type_ = from.type_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void RawInputCommandBuffer::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:usx.geofactions.RawInputCommandBuffer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RawInputCommandBuffer::CopyFrom(const RawInputCommandBuffer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:usx.geofactions.RawInputCommandBuffer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RawInputCommandBuffer::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_dualstickrawinputcommandbuffer()) {
    if (!dualstickrawinputcommandbuffer_->IsInitialized()) return false;
  }
  return true;
}

void RawInputCommandBuffer::InternalSwap(RawInputCommandBuffer* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  uuid_.Swap(&other->uuid_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RawInputCommandBuffer, type_)
      + sizeof(RawInputCommandBuffer::type_)
      - PROTOBUF_FIELD_OFFSET(RawInputCommandBuffer, dualstickrawinputcommandbuffer_)>(
          reinterpret_cast<char*>(&dualstickrawinputcommandbuffer_),
          reinterpret_cast<char*>(&other->dualstickrawinputcommandbuffer_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RawInputCommandBuffer::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace geofactions
}  // namespace usx
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::usx::geofactions::RawInputCommandBuffer* Arena::CreateMaybeMessage< ::usx::geofactions::RawInputCommandBuffer >(Arena* arena) {
  return Arena::CreateMessageInternal< ::usx::geofactions::RawInputCommandBuffer >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
