// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityCommandBuffer.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "SecurityCommandBuffer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace CommandBuffers {

namespace {

const ::google::protobuf::Descriptor* SecurityCommandBuffer_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SecurityCommandBuffer_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* SecurityCommandBuffer_SecurityCommandBufferType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_SecurityCommandBuffer_2eproto() {
  protobuf_AddDesc_SecurityCommandBuffer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "SecurityCommandBuffer.proto");
  GOOGLE_CHECK(file != NULL);
  SecurityCommandBuffer_descriptor_ = file->message_type(0);
  static const int SecurityCommandBuffer_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecurityCommandBuffer, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecurityCommandBuffer, uuid_),
  };
  SecurityCommandBuffer_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SecurityCommandBuffer_descriptor_,
      SecurityCommandBuffer::default_instance_,
      SecurityCommandBuffer_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecurityCommandBuffer, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SecurityCommandBuffer, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SecurityCommandBuffer));
  SecurityCommandBuffer_SecurityCommandBufferType_descriptor_ = SecurityCommandBuffer_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_SecurityCommandBuffer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SecurityCommandBuffer_descriptor_, &SecurityCommandBuffer::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_SecurityCommandBuffer_2eproto() {
  delete SecurityCommandBuffer::default_instance_;
  delete SecurityCommandBuffer_reflection_;
}

void protobuf_AddDesc_SecurityCommandBuffer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033SecurityCommandBuffer.proto\022\016CommandBu"
    "ffers\"\246\001\n\025SecurityCommandBuffer\022M\n\004type\030"
    "\001 \002(\0162\?.CommandBuffers.SecurityCommandBu"
    "ffer.SecurityCommandBufferType\022\014\n\004UUID\030\002"
    " \001(\t\"0\n\031SecurityCommandBufferType\022\010\n\004JOI"
    "N\020\000\022\t\n\005LEAVE\020\001", 214);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SecurityCommandBuffer.proto", &protobuf_RegisterTypes);
  SecurityCommandBuffer::default_instance_ = new SecurityCommandBuffer();
  SecurityCommandBuffer::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_SecurityCommandBuffer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_SecurityCommandBuffer_2eproto {
  StaticDescriptorInitializer_SecurityCommandBuffer_2eproto() {
    protobuf_AddDesc_SecurityCommandBuffer_2eproto();
  }
} static_descriptor_initializer_SecurityCommandBuffer_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* SecurityCommandBuffer_SecurityCommandBufferType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SecurityCommandBuffer_SecurityCommandBufferType_descriptor_;
}
bool SecurityCommandBuffer_SecurityCommandBufferType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const SecurityCommandBuffer_SecurityCommandBufferType SecurityCommandBuffer::JOIN;
const SecurityCommandBuffer_SecurityCommandBufferType SecurityCommandBuffer::LEAVE;
const SecurityCommandBuffer_SecurityCommandBufferType SecurityCommandBuffer::SecurityCommandBufferType_MIN;
const SecurityCommandBuffer_SecurityCommandBufferType SecurityCommandBuffer::SecurityCommandBufferType_MAX;
const int SecurityCommandBuffer::SecurityCommandBufferType_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int SecurityCommandBuffer::kTypeFieldNumber;
const int SecurityCommandBuffer::kUUIDFieldNumber;
#endif  // !_MSC_VER

SecurityCommandBuffer::SecurityCommandBuffer()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SecurityCommandBuffer::InitAsDefaultInstance() {
}

SecurityCommandBuffer::SecurityCommandBuffer(const SecurityCommandBuffer& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SecurityCommandBuffer::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
  uuid_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SecurityCommandBuffer::~SecurityCommandBuffer() {
  SharedDtor();
}

void SecurityCommandBuffer::SharedDtor() {
  if (uuid_ != &::google::protobuf::internal::kEmptyString) {
    delete uuid_;
  }
  if (this != default_instance_) {
  }
}

void SecurityCommandBuffer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SecurityCommandBuffer::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SecurityCommandBuffer_descriptor_;
}

const SecurityCommandBuffer& SecurityCommandBuffer::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_SecurityCommandBuffer_2eproto();
  return *default_instance_;
}

SecurityCommandBuffer* SecurityCommandBuffer::default_instance_ = NULL;

SecurityCommandBuffer* SecurityCommandBuffer::New() const {
  return new SecurityCommandBuffer;
}

void SecurityCommandBuffer::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    type_ = 0;
    if (has_uuid()) {
      if (uuid_ != &::google::protobuf::internal::kEmptyString) {
        uuid_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SecurityCommandBuffer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .CommandBuffers.SecurityCommandBuffer.SecurityCommandBufferType type = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::CommandBuffers::SecurityCommandBuffer_SecurityCommandBufferType_IsValid(value)) {
            set_type(static_cast< ::CommandBuffers::SecurityCommandBuffer_SecurityCommandBufferType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_UUID;
        break;
      }

      // optional string UUID = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_UUID:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uuid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->uuid().data(), this->uuid().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SecurityCommandBuffer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required .CommandBuffers.SecurityCommandBuffer.SecurityCommandBufferType type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional string UUID = 2;
  if (has_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->uuid().data(), this->uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->uuid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SecurityCommandBuffer::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required .CommandBuffers.SecurityCommandBuffer.SecurityCommandBufferType type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional string UUID = 2;
  if (has_uuid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->uuid().data(), this->uuid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->uuid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SecurityCommandBuffer::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required .CommandBuffers.SecurityCommandBuffer.SecurityCommandBufferType type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
    }

    // optional string UUID = 2;
    if (has_uuid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->uuid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SecurityCommandBuffer::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SecurityCommandBuffer* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SecurityCommandBuffer*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SecurityCommandBuffer::MergeFrom(const SecurityCommandBuffer& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_uuid()) {
      set_uuid(from.uuid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SecurityCommandBuffer::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SecurityCommandBuffer::CopyFrom(const SecurityCommandBuffer& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SecurityCommandBuffer::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void SecurityCommandBuffer::Swap(SecurityCommandBuffer* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(uuid_, other->uuid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SecurityCommandBuffer::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SecurityCommandBuffer_descriptor_;
  metadata.reflection = SecurityCommandBuffer_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace CommandBuffers

// @@protoc_insertion_point(global_scope)
